{{-
name = "Delete" + entity.name;
class_name = name + "Interactor";
-}}
using System;
using System.Threading.Tasks;
using {{component_fullname component 'Gateways'}};
using {{component_fullname component 'Mappers'}};
using {{component_fullname component 'RequestModels' entity.name | pluralize}};
using {{component_fullname component 'Validators'}};
using {{entity.callsite}};

namespace {{component_fullname component 'Interactors' entity.name | pluralize}}
{
    internal class {{class_name}} : IInteractor<{{name}}Command>
    {
        private readonly IValidator<{{name}}Command> validator;
        private readonly IDeleteGateway<{{entity.name}}> repository;
        private readonly IGetByIdGateway<{{entity.name}}> getByIdRepository;

        public {{class_name}}(
            IValidator<{{name}}Command> validator,
            IDeleteGateway<{{entity.name}}> repository,
            IGetByIdGateway<{{entity.name}}> getByIdRepository)
        {
            this.validator = validator;
            this.repository = repository;
            this.getByIdRepository = getByIdRepository;
        }

        public async Task<Response> ExecuteUseCase({{name}}Command requestModel)
        {
            Response response = validator.Validate(requestModel);
            if (response.IsValid)
            {
                try
                {
                    {{entity.name}} entity = getByIdRepository.GetById(requestModel.Id);
                    if (entity == null)
                    {
                        response.AddError(ErrorCodes.NotFound, $"{{entity.name}} resource ({requestModel.Id}) not found.");
                        return response;
                    }

                    bool deleted = await repository.Delete(entity);
                    response.SetParameter(entity);
                    if (!deleted)
                    {
                        response.AddError(ErrorCodes.InternalServerError, $"Failed to delete entity id {requestModel.Id}");
                    }
                }
                catch (Exception exception)
                {
                    response.AddError(ErrorCodes.InternalServerError, exception.Message);
                }
            }

            return response;
        }
    }
}
